POST http://localhost:3060/api/users/
Content-Type: application/json

{"user":
    { 
        "username": "nam1262",   
        "email": "nam222@gmail.com",  
        "password": "12323"  
    }
}

###
POST http://localhost:3060/api/users/login
Content-Type: application/json

{
    "user":
    { 
        "email": "nam222222222222@.scom",  
        "password": "12323"  
    }
}
###
GET http://localhost:3060/api/user
Content-Type: application/json
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmE1OTY2MDlmOTFhYzVkMjFiZWRjOTAiLCJpYXQiOjE2NTUwMTkxMTUsImV4cCI6MTY1NTA1NTExNX0.vxXapWrPxpnItsAD1Y-3yYrms7n3o6qo05TQzTueyvA

###
PUT http://localhost:3060/api/user
Content-Type: application/json
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmE0YzBiMWFkYzJmNzk2Y2E4ZjY5MjkiLCJpYXQiOjE2NTUwODU4ODksImV4cCI6MTY1NTEyMTg4OX0.zDoZnK5IE71RDrkvbiFoXB9YLhwcz6_KSOE7KjXREH0

{"user": {"email": "nam222222222222@.scom", "bio": "bio2", "image": "img", "username": "nam12836772"}}

###
GET http://localhost:3060/api/profiles/hoainam07

###
POST http://localhost:3060/api/profiles/nam1262/follow
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmE1OTY2MDlmOTFhYzVkMjFiZWRjOTAiLCJpYXQiOjE2NTUwMTkxMTUsImV4cCI6MTY1NTA1NTExNX0.vxXapWrPxpnItsAD1Y-3yYrms7n3o6qo05TQzTueyvA
###
DELETE http://localhost:3060/api/profiles/nam1262/follow
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmE1OTY2MDlmOTFhYzVkMjFiZWRjOTAiLCJpYXQiOjE2NTUwMTkxMTUsImV4cCI6MTY1NTA1NTExNX0.vxXapWrPxpnItsAD1Y-3yYrms7n3o6qo05TQzTueyvA


###
POST http://localhost:3060/api/articles
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmE0YzBiMWFkYzJmNzk2Y2E4ZjY5MjkiLCJpYXQiOjE2NTUwNDUwNjYsImV4cCI6MTY1NTA4MTA2Nn0.kIhtkT9gV2P3cwVJVZUxU93EM0xIf6uYKukotPtuMgE
Content-Type: application/json

{"article": 
    {
        "description": " wordsfld",
        "body": "hello world", 
        "tagList": ["hello wdorld"],
        "title": "xin chào thế giớisda"
    }
}

###
GET http://localhost:3060/api/articles/feed?limit=10&offset=0
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmE0YzBiMWFkYzJmNzk2Y2E4ZjY5MjkiLCJpYXQiOjE2NTUwNDUwNjYsImV4cCI6MTY1NTA4MTA2Nn0.kIhtkT9gV2P3cwVJVZUxU93EM0xIf6uYKukotPtuMgE

###
GET http://localhost:3060/api/articles?limit=10&offset=0&favorited=ng245345345
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmE0YzBiMWFkYzJmNzk2Y2E4ZjY5MjkiLCJpYXQiOjE2NTUwNDUwNjYsImV4cCI6MTY1NTA4MTA2Nn0.kIhtkT9gV2P3cwVJVZUxU93EM0xIf6uYKukotPtuMgE

###
GET http://localhost:3060/api/articles/xin-chao-the-gioi-ZHW2nJ8io
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmE0YzBiMWFkYzJmNzk2Y2E4ZjY5MjkiLCJpYXQiOjE2NTUwNDUwNjYsImV4cCI6MTY1NTA4MTA2Nn0.kIhtkT9gV2P3cwVJVZUxU93EM0xIf6uYKukotPtuMgE


###
PUT http://localhost:3060/api/articles/xin-chao-the-gioi
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmE0YzBiMWFkYzJmNzk2Y2E4ZjY5MjkiLCJpYXQiOjE2NTUwODU4ODksImV4cCI6MTY1NTEyMTg4OX0.zDoZnK5IE71RDrkvbiFoXB9YLhwcz6_KSOE7KjXREH0
Content-Type: application/json

{ "article": {"title": "string hello", "description": "string","body": "string"}}

###
DELETE http://localhost:3060/api/articles/xin-chao-the-gioi
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmE0YzBiMWFkYzJmNzk2Y2E4ZjY5MjkiLCJpYXQiOjE2NTUwODU4ODksImV4cCI6MTY1NTEyMTg4OX0.zDoZnK5IE71RDrkvbiFoXB9YLhwcz6_KSOE7KjXREH0



###
GET http://localhost:3060/api/articles/xin-chao-the-gioisda/comments
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmE1OTY2MDlmOTFhYzVkMjFiZWRjOTAiLCJpYXQiOjE2NTUwOTU1NjcsImV4cCI6MTY1NTEzMTU2N30.fNeiSBWT-X8D6_sYlAh8DtoUZQx1LldiQV5GfYjiVvc
Content-Type: application/json

###
POST http://localhost:3060/api/articles/xin-chao-the-gioisda/comments
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmE0YzBiMWFkYzJmNzk2Y2E4ZjY5MjkiLCJpYXQiOjE2NTUwODU4ODksImV4cCI6MTY1NTEyMTg4OX0.zDoZnK5IE71RDrkvbiFoXB9YLhwcz6_KSOE7KjXREH0
Content-Type: application/json

{
  "comment": {
    "body": "xin-chao-the-gioisda"
  }
}

###
DELETE http://localhost:3060/api/articles/xin-chao-the-gioisda/comments/62a6bead70f199bc4909a8a7
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmE0YzBiMWFkYzJmNzk2Y2E4ZjY5MjkiLCJpYXQiOjE2NTUxMDM1ODcsImV4cCI6MTY1NTEzOTU4N30.Q_6rkifGPy6zzuPfXAziFk4JXCsb--57MKdEAIbvVHI
Content-Type: application/json


### 
POST http://localhost:3060/api/articles/xin-chao-the-gioisda/favorite
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmE0YzBiMWFkYzJmNzk2Y2E4ZjY5MjkiLCJpYXQiOjE2NTUxMDM1ODcsImV4cCI6MTY1NTEzOTU4N30.Q_6rkifGPy6zzuPfXAziFk4JXCsb--57MKdEAIbvVHI

### 
DELETE http://localhost:3060/api/articles/xin-chao-the-gioisda/favorite
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmE0YzBiMWFkYzJmNzk2Y2E4ZjY5MjkiLCJpYXQiOjE2NTUxMDM1ODcsImV4cCI6MTY1NTEzOTU4N30.Q_6rkifGPy6zzuPfXAziFk4JXCsb--57MKdEAIbvVHI


### 
GET http://localhost:3060/api/tags









################################################################################
GET https://api.realworld.io/api/user
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbTFzc3Nkd3NzZEAuc2NvbSIsImlhdCI6MTY1NDk1MDUzOCwiZXhwIjoxNjU0OTg2NTM4fQ.OT6IsbD25vQuIFzeu9kWHYS2LgXXxh4c887IytFST_w


###

POST https://api.realworld.io/api/users
Content-Type: application/json  

{"user": { "username": "SSddsadsfsSS",   
        "email": "namsdffdsf1@.scom",  
        "password": "123"  
    }
}


###
GET https://api.realworld.io/api/user
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbTIxNTU0MzY5NEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6Ik5ndXllZW54IiwiaWF0IjoxNjU0OTUyNzk2LCJleHAiOjE2NjAxMzY3OTZ9.4a5hhKcTzwNeXusPyytuG4HEoQfZy9eu63H79DhrzI4

###
PUT https://api.realworld.io/api/user
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbTIxNTU0MzY5NEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6Ik5ndXllZW54IiwiaWF0IjoxNjU0OTUzMDU0LCJleHAiOjE2NjAxMzcwNTR9.cYlfGukkL_9z2CDC9PojjzCqkeL_ZpBa6U2vk4TSbdk

{"user": {"email": "nam215543694@gmail.com", "bio": "fdsf", "image": "fdsfsadasd", "username": "Nguyeenx"}}


###
POST https://api.realworld.io/api/profiles/Nguyeenx/follow
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbTIxNTU0MzY5NEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6Ik5ndXllZW54IiwiaWF0IjoxNjU1MDE0ODM3LCJleHAiOjE2NjAxOTg4Mzd9.BxgT-RoGUyF2LGfGYM7Uh3Le5fpC_FL5DDJgma7VflM
###
DELETE https://api.realworld.io/api/profiles/Gerome/follow
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbTIxNTU0MzY5NEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6Ik5ndXllZW54IiwiaWF0IjoxNjU1MDE0ODM3LCJleHAiOjE2NjAxOTg4Mzd9.BxgT-RoGUyF2LGfGYM7Uh3Le5fpC_FL5DDJgma7VflM
Content-Type: application/json  
### 
POST https://api.realworld.io/api/articles
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbTIxNTU0MzY5NEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6Ik5ndXllZW54IiwiaWF0IjoxNjU1MDE3ODQ4LCJleHAiOjE2NjAyMDE4NDh9.GO-BOwMG_Om3xobHb0c89qiyKPEGZRS-xGH8BuQwp0g
Content-Type: application/json

{"article": 
    {
        "description": "hello world 12",
        "body": "hello world", 
        "tagList": ["hello world"],
        "title": "shelrewrwerlo"
    }
}


###
GET https://api.realworld.io/api/articles?author=Gerome&tag=implementations


### 
GET https://api.realworld.io/api/articles/feed?limit=10&offset=0?tag=welcome
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbTIxNTU0MzY5NEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6Ik5ndXllZW54IiwiaWF0IjoxNjU1MDQ1NzM1LCJleHAiOjE2NjAyMjk3MzV9.mVtF_mH8UIqE8PyvWTVYRuu6WRtHMU_-L25WSszVp24

###
GET https://api.realworld.io/api/articles/Create-a-new-implementation-1
authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbTIxNTU0MzY5NEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6Ik5ndXllZW54IiwiaWF0IjoxNjU1MDQ1NzM1LCJleHAiOjE2NjAyMjk3MzV9.mVtF_mH8UIqE8PyvWTVYRuu6WRtHMU_-L25WSszVp24

